import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/providers/theme-provider'
import ReactQueryProvider from '@/providers/ReactQueryProvider'
import {
  Golpa,
  GolpaBold,
  GramophoneClean,
  GramophoneGrunge,
  GramophoneStone,
  Kaghaz,
  Potk,
  Shabnam,
  SnapWebReg,
  primaryFont,
} from '@/lib/fonts'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pixelgram',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir="rtl" suppressHydrationWarning>
      <body className={`${SnapWebReg.className}`}>
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
